import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react';
// import Test from './test';

import {Box, Text} from '@chakra-ui/react';


// Components
import Products from '../components/Products';

export default function Home() {

  // const authInput = prompt('Enter password');

const [isAuthorized, setIsAuthorized] = useState(false)

const submitAuth = () => {
  setIsAuthorized(true)
}

  return (
    <Box sx={styles.container}>
      <Head>
        <title>JC DB</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>


        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet"/>


<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet"/>


<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Antonio:wght@100&display=swap" rel="stylesheet"/>


      </Head>
   <Box>
<Products/>
   </Box>
    </Box>
  )
}
const styles = {
  container: {
   background: '#1F1E1E'
    
  }
}

