import Head from 'next/head'
import Image from 'next/image'


import {Box, Text} from '@chakra-ui/react';


// Components
import Products from '../components/Products';

export default function Home() {
  return (
    <Box sx={styles.container}>
      <Head>
        <title>JC DB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
   <Box>
<Products/>
   </Box>
    </Box>
  )
}
const styles = {
  container: {
   background: '#1F1E1E'
    
  }
}

